// characters/gertie/art.js — Grandma Gertie's art: a painted SVG sprite sheet for Gertie
// herself (gertie.svg, generated by sheet-svg.js from poses.js) riding a fully procedural
// turbo scooter (scooter.js), with procedural props in her sprite hands, a live rim light
// from the stage, phase-driven anticipation / impact / follow-through, and custom fx.
import * as kit from '../../shared/art/kit.js';
import { FRAME, POSES, SEAT, TEETH, joints } from './poses.js';
import {
  OUT, TAU, clamp, lerp, easeOut, easeIn, backOut, spring, rotL, paint, S, MAT, GEO, scooterBack,
  cane, handbag, purse, umbrella, hatpin, rollingPin, grabber, sprayMist, backfire, steam, heart, denturesFallback, gertieFallback,
} from './scooter.js';

const PAL = {
  main: '#b88ddc', effect: '#ffd166', outline: OUT,
  scooter: '#e8505b', scooterDark: '#a52f45', scooterLight: '#ff9c94',
  spark: '#ffd166', petal: '#fffdf4', pink: '#ff8fb0',
};

// Pose-table joints per sheet frame (deterministic; computed once).
const JOINTS = POSES.map((p) => joints(p));

const seq = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);

// ── Phase helpers ────────────────────────────────────────────────────────────
/** Windup → strike → settle curve: -1 at full anticipation, +1 at impact, 0 at rest. */
function swing(ph, t) {
  if (ph === 'startup' || ph === 'charge') return -easeOut(clamp(t, 0, 1));
  if (ph === 'active') return lerp(0.6, 1, backOut(clamp(t * 1.4, 0, 1)));
  if (ph === 'recovery') return 1 - easeOut(clamp(t, 0, 1));
  return 0;
}

/** First non-grab strike hitbox of the current (validated) move, body space. */
function strikeBox(m) {
  const hbs = m?.def?.hitboxes;
  if (!Array.isArray(hbs) || !hbs.length) return null;
  return hbs.find((h) => h.kind !== 'grab') || hbs[0];
}
const boxCenter = (h) => {
  if (!h) return null;
  if (h.x1 !== undefined) return [(h.x1 + h.x2) / 2, (h.y1 + h.y2) / 2];
  return [h.x, h.y];
};

/**
 * The scooter rig for this frame: tilt (rad, + = nose down) about a pivot, an optional
 * spin about a center, vertical squash and the sprite's own bob/offsets.
 */
function rigFor(v, info, cache) {
  const m = v.move, anim = m?.anim, ph = m?.phase, pt = m?.phaseT ?? 0;
  const t = info.time, mo = info.motion;
  const r = { tilt: 0, pivot: [0, -12], spin: 0, spinC: [0, -46], sy: 1 - mo.squash * 0.1, gx: 0, gy: mo.squash * 3, dy: 0, shake: 0, rev: false };
  // idle breathing (Gertie) + the motor's faint hum (scooter)
  r.gy += Math.sin(t * 2.3) * 0.7;
  r.dy += Math.sin(t * 31) * 0.12;
  const st = v.state;
  if (st === 'run' || (st === 'idle' && Math.abs(v.vx) > 0.5)) {
    const d = cache.dist || 0;
    r.dy += -Math.abs(Math.sin(d * 0.09)) * 1.1;
    r.tilt += -mo.lean * 0.035;
    r.gy += Math.sin(d * 0.18) * 0.6;
  }
  if (!v.grounded && (st === 'air' || st === 'jump' || st === 'fall' || st === 'helpless' || st === 'attack')) {
    r.tilt += clamp(v.vy * 0.014, -0.14, 0.18);
    r.pivot = [0, -30];
  }
  // Readable state silhouettes: the sprite poses are subtle at game scale, so the whole
  // rig squashes, tips, spins or rocks per state (stateCues() adds the overlays).
  const sf = v.stateFrame || 0;
  if (st === 'crouch') { r.sy *= 0.84; r.gy += 5; r.gx += 4; r.tilt += 0.08; r.pivot = [GEO.front[0], 0]; }
  if (st === 'jumpsquat') { r.sy *= 0.86; r.gy += 4; r.tilt -= 0.06; r.pivot = [GEO.rear[0], 0]; }
  if (st === 'land') { const k = 1 - Math.min(1, sf / 8); r.sy *= 1 - 0.14 * k; r.gy += 4 * k; }
  if (st === 'shield') { r.tilt -= 0.1; r.pivot = [GEO.rear[0], 0]; r.gx -= 3; }
  if (st === 'roll') { r.spin = -TAU * easeOut(Math.min(1, sf / 22)); r.spinC = [0, -46]; r.sy *= 0.9; }
  if (st === 'airdodge') { r.spin = -TAU * 0.25 * Math.sin(Math.min(1, sf / 18) * Math.PI); r.spinC = [0, -50]; }
  if (st === 'spotdodge') { r.gx -= 6 * Math.sin(Math.min(1, sf / 16) * Math.PI); r.tilt -= 0.12 * Math.sin(Math.min(1, sf / 16) * Math.PI); r.pivot = [GEO.rear[0], 0]; }
  if (st === 'helpless') { r.tilt += 0.32 + Math.sin(t * 9) * 0.06; r.pivot = [0, -40]; r.shake = 0.6; }
  if (st === 'grabbed') { r.tilt -= 0.18 + Math.sin(t * 14) * 0.08; r.pivot = [0, -40]; r.shake = 1; }
  if (st === 'respawn') r.gy -= 2 + Math.sin(t * 3) * 2;
  if (st === 'hitstun' || st === 'hurt') {
    if (v.tumble) { r.spin = t * -11; r.spinC = [0, -50]; } else { r.tilt -= 0.22; r.shake = 1.2; }
  }
  if (st === 'glide') { r.tilt += Math.sin(t * 1.7) * 0.07; r.pivot = [0, -110]; }
  if (st === 'stunned' || st === 'shieldbreak') { r.tilt += Math.sin(t * 4) * 0.16; r.pivot = [0, 0]; r.gx += Math.sin(t * 4 + 1) * 3; }
  if (st === 'roll' || st === 'spotdodge' || st === 'airdodge') r.gx += Math.sin(t * 30) * 0.6;
  if (!anim) return r;
  const sw = swing(ph, pt);
  switch (anim) {
    case 'stomp':                                   // front rears up, then slams down
      if (ph === 'startup' || ph === 'charge') { r.tilt = -0.24 * easeOut(pt) - (ph === 'charge' ? 0.04 * Math.sin(t * 30) : 0); r.pivot = [GEO.rear[0], 0]; }
      else if (ph === 'active') { r.sy *= 0.9; r.gy += 3; r.shake = 1.5; }
      else r.tilt = -0.05 * (1 - pt) * Math.sin(pt * 12);
      break;
    case 'wheelie':
      if (ph === 'startup') { r.tilt = -0.3 * easeOut(pt); r.pivot = [GEO.rear[0], 0]; }
      else if (ph === 'active') { r.spin = -TAU * (0.5 - 0.5 * Math.cos(Math.PI * pt)); r.tilt = -0.3; r.pivot = [GEO.rear[0], 0]; }
      else { r.tilt = -0.3 * (1 - easeOut(pt)); r.pivot = [GEO.rear[0], 0]; }
      break;
    case 'slam': r.tilt = lerp(0.1, 0.4, easeOut(Math.min(1, m.frame / 10))); r.pivot = [0, -40]; if (ph === 'active') r.shake = 0.8; break;
    case 'ram':
      if (ph === 'startup') { r.shake = 1.4; r.tilt = -0.05; r.rev = true; }
      else if (ph === 'active') { r.tilt = 0.06 + Math.sin(t * 40) * 0.01; r.gx = 2; r.rev = true; }
      else r.tilt = 0.06 * (1 - easeOut(pt));
      break;
    case 'sputter': r.shake = 2.4 * (1 - pt * 0.6); r.tilt = -0.1 + Math.sin(t * 22) * 0.06; r.pivot = [GEO.rear[0], 0]; r.sy *= 0.94; break;
    case 'toss': r.tilt += sw * 0.08; r.gx += sw * 3; r.pivot = [0, -20]; break;
    case 'knit': r.tilt += 0.08; r.pivot = [GEO.front[0], 0]; r.gy += 2; break;
    case 'exhaust': r.tilt = ph === 'active' ? 0.12 : ph === 'recovery' ? 0.12 * (1 - easeOut(pt)) : -0.04 * pt; r.pivot = [0, -40]; break;
    case 'lift': r.tilt = Math.sin(t * 9) * 0.05; r.pivot = [0, -110]; break;
    case 'umbrella': if (ph === 'active') r.dy -= 3 * (1 - pt); else if (ph !== 'recovery') { r.sy *= 1 - 0.05 * pt; r.gy += 2 * pt; } break;
    case 'handbag': case 'cane': case 'pin':
      r.tilt += sw * 0.05; r.gx += sw * 2.2; break;
    case 'jab': case 'grab': r.gx += sw * 1.6; break;
    case 'shoo': r.gx += sw * 4; r.tilt += sw * 0.1; r.pivot = [0, -10]; break;
    case 'sitdown': r.tilt += Math.max(0, sw) * 0.22 - Math.max(0, -sw) * 0.12; r.pivot = [GEO.front[0], 0]; if (ph === 'active') r.shake = 1.2; break;
    case 'shoulder': r.tilt -= Math.max(0, sw) * 0.16; r.pivot = [GEO.rear[0], 0]; break;
    case 'upyougo': r.tilt -= Math.max(0, sw) * 0.12; r.gy -= Math.max(0, sw) * 4; r.pivot = [GEO.rear[0], 0]; break;
    case 'lecture': r.gy += Math.abs(Math.sin(t * 7)) * -3; r.tilt += Math.sin(t * 3.5) * 0.06; break;
    case 'tea': r.gy += Math.sin(t * 1.4) * 0.4; break;
    default: break;
  }
  return r;
}

// ── State cues (unrotated overlays: stun stars, sweat, halo, scolding bubble) ──
const HEAD = [-8, -96];

function star5(c, x, y, r, col, rot = 0) {
  kit.starPath(c, x, y, 5, r, r * 0.45, rot);
  c.fillStyle = col; c.fill();
  c.lineWidth = 1.4; c.strokeStyle = OUT; c.stroke();
}

function sweat(c, x, y, s, alpha = 1) {
  c.save(); c.globalAlpha *= alpha;
  kit.droplet(c, x, y, 3.2 * s, '#9fd8ff', 0, OUT);
  c.restore();
}

function stateCues(c, v, info) {
  const st = v.state, t = info.time;
  if (st === 'stunned' || st === 'shieldbreak') {
    // stars and a tiny bird circling her hat
    const cx = HEAD[0], cy = HEAD[1] - 28, rx = 34, ry = 10;
    for (let i = 0; i < 4; i++) {
      const a = t * 4 + (i * TAU) / 4;
      const x = cx + Math.cos(a) * rx, y = cy + Math.sin(a) * ry, k = 0.75 + 0.25 * Math.sin(a);
      if (i === 3) {
        c.save(); c.translate(x, y); c.scale(Math.cos(a) > 0 ? -1 : 1, 1);
        c.beginPath(); c.ellipse(0, 0, 7 * k, 5.4 * k, 0, 0, TAU); c.fillStyle = '#ffe36b'; c.fill(); c.lineWidth = 1.3; c.strokeStyle = OUT; c.stroke();
        c.beginPath(); c.moveTo(-7 * k, -0.5); c.lineTo(-11 * k, 1); c.lineTo(-7 * k, 2.5); c.fillStyle = '#ff9a3c'; c.fill();
        c.restore();
      } else star5(c, x, y, 8.5 * k, i % 2 ? '#fff3a8' : '#ffd166', t * 3 + i);
    }
    return;
  }
  if (st === 'helpless') {
    for (let i = 0; i < 2; i++) { const u = (t * 1.6 + i * 0.5) % 1; sweat(c, HEAD[0] + 16 + i * 6, HEAD[1] - 8 + u * 14, 1, 1 - u); }
    // scribble of worry above the hat
    c.save(); c.strokeStyle = OUT; c.lineWidth = 1.8; c.lineCap = 'round';
    c.beginPath();
    for (let i = 0; i <= 24; i++) { const a = i * 0.9 + t * 6, x = HEAD[0] + Math.cos(a) * (7 + (i % 3)) + i * 0.4 - 5, y = HEAD[1] - 34 + Math.sin(a) * 4; i ? c.lineTo(x, y) : c.moveTo(x, y); }
    c.stroke(); c.restore();
    // engine coughing smoke
    for (let i = 0; i < 3; i++) {
      const u = (t * 1.2 + i / 3) % 1;
      c.save(); c.globalAlpha = 0.55 * (1 - u);
      kit.circle(c, GEO.pipe[0] - 6 - u * 22, GEO.pipe[1] - u * 16, 4 + u * 7, '#8f8499', { outline: null });
      c.restore();
    }
    return;
  }
  if (st === 'grabbed') {
    sweat(c, HEAD[0] + 18, HEAD[1] - 6, 1.1);
    kit.blinkIcon(c, HEAD[0] - 18, HEAD[1] - 32, 'alert', t, { size: 15, color: '#ff5a64', rate: 3 });
    return;
  }
  if (st === 'respawn') {
    c.save();
    c.globalCompositeOperation = 'lighter';
    kit.glow(c, HEAD[0], HEAD[1] - 30, 22, '#ffe9a0', 0.45);
    c.restore();
    c.save(); c.lineWidth = 3.4; c.strokeStyle = '#ffd166';
    c.beginPath(); c.ellipse(HEAD[0], HEAD[1] - 30 + Math.sin(t * 3) * 1.5, 14, 4, 0, 0, TAU); c.stroke();
    c.lineWidth = 1.2; c.strokeStyle = '#fff8dc'; c.stroke();
    c.restore();
    return;
  }
  if (v.move?.anim === 'lecture') {
    // scolding speech bubble with a wagging "!"
    const bx = HEAD[0] + 34, by = HEAD[1] - 34, wag = Math.sin(t * 7) * 0.15;
    c.save();
    c.translate(bx, by); c.rotate(wag);
    kit.roundRectPath(c, -15, -12, 30, 22, 8);
    c.fillStyle = '#fffdf4'; c.fill(); c.lineWidth = 2; c.strokeStyle = OUT; c.stroke();
    c.beginPath(); c.moveTo(-8, 9); c.lineTo(-16, 18); c.lineTo(-1, 10); c.closePath(); c.fillStyle = '#fffdf4'; c.fill(); c.stroke();
    c.fillStyle = '#e8505b';
    for (const dx of [-5, 5]) { kit.capsulePath(c, dx, -6, dx, 0, 2.4); c.fill(); c.beginPath(); c.arc(dx, 5, 2.2, 0, TAU); c.fill(); }
    c.restore();
  }
}

// ── Sprite rim light ─────────────────────────────────────────────────────────
/** A band just inside the sprite's outline on the lit side (shape minus itself shifted). */
function spriteRim(c, info, idx, L) {
  const img = info.assets?.sheet;
  if (!img || !L.rim || info.quality === 'low') return;
  const cache = info.cache;
  if (cache.rimCv === undefined) cache.rimCv = kit.makeCanvas(FRAME.w, FRAME.h) || null;
  const cv = cache.rimCv;
  if (!cv) return;
  const g = cv.getContext('2d');
  const W = FRAME.w, H = FRAME.h, sx = (idx % FRAME.cols) * W, sy = Math.floor(idx / FRAME.cols) * H;
  const o1 = 6.5, w = 5;                            // source px: skip the baked outline, then the band
  g.setTransform(1, 0, 0, 1, 0, 0);
  g.globalAlpha = 1;
  g.globalCompositeOperation = 'source-over';
  g.clearRect(0, 0, W, H);
  g.drawImage(img, sx, sy, W, H, -L.x * o1, -L.y * o1, W, H);
  g.globalCompositeOperation = 'destination-out';
  g.drawImage(img, sx, sy, W, H, -L.x * (o1 + w), -L.y * (o1 + w), W, H);
  g.globalCompositeOperation = 'destination-in';
  g.drawImage(img, sx, sy, W, H, 0, 0, W, H);
  g.globalCompositeOperation = 'source-in';
  g.fillStyle = L.rim; g.fillRect(0, 0, W, H);
  g.globalCompositeOperation = 'source-over';
  c.save();
  c.globalCompositeOperation = 'screen';            // light adds up: brightens the lit edge, never muddies it
  c.globalAlpha *= 0.8;
  c.drawImage(cv, 0, 0, W, H, -FRAME.anchor[0] * FRAME.scale, -FRAME.anchor[1] * FRAME.scale, W * FRAME.scale, H * FRAME.scale);
  c.restore();
}

// ── Props (in front of / behind the sprite) ──────────────────────────────────
function props(c, v, info, J, off, L, layer) {
  const m = v.move, anim = m?.anim, ph = m?.phase, pt = m?.phaseT ?? 0, t = info.time;
  const hf = [SEAT.x + J.hF[0] + off[0], SEAT.y + J.hF[1] + off[1]];
  const hb = strikeBox(m);
  const front = layer === 'front';
  if (v.state === 'glide' && front) {
    const sway = Math.sin(t * 1.7) * 0.06;
    umbrella(c, hf[0], hf[1], hf[0] + 3, hf[1] - 30, 40, 1, sway, L, t);
    return;
  }
  if (v.state === 'grabbing' && front) { grabber(c, hf[0], hf[1], 40, -54 + Math.sin(t * 6) * 1.5, 1, L); return; }
  if (!anim) return;
  switch (anim) {
    case 'cane': {
      if (!front) return;
      const tip = hb?.x2 !== undefined ? [hb.x2, hb.y2] : [104, -40];
      const aHit = Math.atan2(tip[1] - hf[1], tip[0] - hf[0]), lenHit = Math.hypot(tip[0] - hf[0], tip[1] - hf[1]) - 4;
      if (ph === 'startup') cane(c, hf[0], hf[1], lerp(-1.9, -2.6, easeOut(pt)), 56, L);
      else if (ph === 'active') {
        kit.smear(c, hf[0], hf[1], lenHit * 0.9, -2.5, aHit, 16, '#fff6dc', 0.75);
        cane(c, hf[0], hf[1], aHit, lenHit, L);
      } else cane(c, hf[0], hf[1], lerp(aHit, 1.0, easeOut(pt)), lerp(lenHit, 54, easeOut(pt)), L);
      return;
    }
    case 'handbag': {
      const ctr = boxCenter(hb) || [76, -54];
      if (ph === 'charge' || ph === 'startup') {
        if (front) return;                            // wound up behind her
        const th = ph === 'charge' ? -t * 13 : lerp(0.6, -2.4, easeOut(pt));
        const R = ph === 'charge' ? 20 : 22;
        handbag(c, hf[0], hf[1], hf[0] - 6 + Math.cos(th) * R, hf[1] - 8 + Math.sin(th) * R * 0.7, th * 0.4, 1, L);
      } else if (front) {
        if (ph === 'active') {
          kit.smear(c, hf[0], hf[1] + 6, Math.hypot(ctr[0] - hf[0], ctr[1] - hf[1] - 6), -2.3, Math.atan2(ctr[1] - hf[1] - 6, ctr[0] - hf[0]), 22, '#e8fff8', 0.7);
          handbag(c, hf[0], hf[1], ctr[0], ctr[1], 0.35, 1.3, L);
        } else {
          const e = easeOut(pt), sw = Math.sin(pt * 9) * (1 - pt) * 0.5;
          handbag(c, hf[0], hf[1], lerp(ctr[0], hf[0] + 6, e), lerp(ctr[1], hf[1] + 18, e), lerp(0.35, sw, e), lerp(1.3, 1, e), L);
        }
      }
      return;
    }
    case 'jab': {
      if (!front) return;
      const ctr = boxCenter(hb) || [48, -52];
      const k = ph === 'startup' ? 0.15 * pt : ph === 'active' ? 1 : 1 - easeOut(pt);
      const x = lerp(hf[0] + 2, ctr[0], k), y = lerp(hf[1] + 9, ctr[1], k);
      if (ph === 'active') kit.smear(c, hf[0], hf[1], Math.hypot(x - hf[0], y - hf[1]), -0.6, Math.atan2(y - hf[1], x - hf[0]), 9, '#fff6dc', 0.6);
      purse(c, hf[0], hf[1], x, y, L);
      return;
    }
    case 'umbrella': case 'lift': {
      if (!front) return;
      const R = hb?.r ?? (anim === 'lift' ? 36 : 44);
      const ctr = boxCenter(hb) || [0, anim === 'lift' ? -120 : -132];
      let open, cx, cy;
      if (anim === 'lift') { open = ph === 'startup' ? easeOut(pt) : 1; cx = hf[0] + 2; cy = hf[1] - 30; }
      else if (ph === 'startup' || ph === 'charge') { open = 0; cx = hf[0] + 1; cy = hf[1] - 26 - pt * 4; }
      else if (ph === 'active') { open = backOut(clamp(pt * 2.5, 0, 1)); cx = lerp(hf[0], ctr[0], 0.6); cy = ctr[1] + R * 0.32; }
      else { open = 1 - easeIn(clamp((pt - 0.55) / 0.45, 0, 1)); cx = lerp(hf[0], ctr[0], 0.6); cy = lerp(ctr[1] + R * 0.32, hf[1] - 30, easeOut(pt)); }
      if (ph === 'active' && anim === 'umbrella') { c.save(); c.globalAlpha *= 1 - pt; kit.rimArc(c, cx, cy - R * 0.3, R * (0.95 + pt * 0.2), { x: 0, y: -1 }, '#ffffff', 4, 0.8, 2.6); c.restore(); }
      umbrella(c, hf[0], hf[1], cx, cy, R * 1.05, open, Math.sin(t * 6) * 0.05 * open, L, t);
      if (anim === 'lift' && ph !== 'recovery') windLines(c, hf[0], hf[1] + 10, t);
      return;
    }
    case 'hatpin': {
      if (!front) return;
      const top = hb?.x2 !== undefined ? [hb.x2, hb.y2] : [8, -140];
      if (ph === 'startup') hatpin(c, hf[0], hf[1], hf[0] + 14 + pt * 4, hf[1] - 10 - pt * 6, 0, L);
      else if (ph === 'active') {
        c.save(); c.globalAlpha *= 0.6; c.strokeStyle = '#ffffff'; c.lineWidth = 10 * (1 - pt) + 2; c.lineCap = 'round';
        c.beginPath(); c.moveTo(hf[0], hf[1] - 6); c.lineTo(top[0], top[1] + 14); c.stroke(); c.restore();
        hatpin(c, hf[0], hf[1], top[0], top[1], 1 - pt * 0.6, L);
      } else hatpin(c, hf[0], hf[1], lerp(top[0], hf[0] + 4, easeOut(pt)), lerp(top[1], hf[1] - 34, easeOut(pt)), 0, L);
      return;
    }
    case 'pin': {
      if (!front) return;
      const ctr = boxCenter(hb) || [62, -50];
      const aHit = Math.atan2(ctr[1] - hf[1], ctr[0] - hf[0]);
      if (ph === 'startup') rollingPin(c, hf[0], hf[1], lerp(-1.6, -2.3, easeOut(pt)), L);
      else if (ph === 'active') { kit.smear(c, hf[0], hf[1], 40, -2.2, aHit + 0.15, 20, '#ffffff', 0.7); rollingPin(c, hf[0], hf[1], aHit + 0.15, L); }
      else rollingPin(c, hf[0], hf[1], lerp(aHit + 0.15, 0.9, easeOut(pt)), L);
      return;
    }
    case 'exhaust': {
      if (front) return;
      const [px, py] = GEO.pipe, ctr = boxCenter(hb) || [-58, -24], R = hb?.r ?? 28;
      const len = Math.abs(ctr[0] - px) + R * 1.1;
      const amt = ph === 'active' ? 1 : ph === 'recovery' ? 1 - easeOut(pt) : 0.25 * (Math.sin(t * 50) > 0 ? 1 : 0.4) * pt;
      backfire(c, px - 1, py, len, amt, t);
      return;
    }
    case 'spray': {
      if (!front) return;
      const noz = [hf[0] + Math.cos(J.aF) * 15, hf[1] + Math.sin(J.aF) * 15];
      const ctr = boxCenter(hb) || [6, -118];
      const amt = ph === 'active' ? 1 : ph === 'recovery' ? 1 - pt : 0;
      sprayMist(c, noz[0], noz[1], ctr[0], ctr[1] - 14, amt, t, info.rng);
      return;
    }
    case 'knit': {
      if (!front || ph === 'startup') return;
      const hbk = [SEAT.x + J.hB[0] + off[0], SEAT.y + J.hB[1] + off[1]];
      const mid = [(hf[0] + hbk[0]) / 2, (hf[1] + hbk[1]) / 2 + 6];
      const sp = v.move.def?.timeline?.find((e) => e.action === 'spawn')?.args || { x: 40, y: -12 };
      c.save(); c.strokeStyle = MAT.yarnA[1]; c.lineWidth = 3.2; c.lineCap = 'round';
      c.beginPath(); c.moveTo(mid[0], mid[1]);
      c.bezierCurveTo(mid[0] + 10, mid[1] + 18 + Math.sin(t * 8) * 4, sp.x - 14, (sp.y ?? -12) - 10, sp.x ?? 40, sp.y ?? -12); c.stroke();
      c.strokeStyle = MAT.yarnA[0]; c.lineWidth = 1.6; c.stroke();
      c.restore();
      return;
    }
    case 'tea': {
      if (!front) return;
      const cup = [hf[0] + 2.6, hf[1] - 7];
      steam(c, cup[0], cup[1], t, ph === 'hold' ? 1 : 0.7);
      if (ph === 'hold') for (let i = 0; i < 3; i++) {
        const u = (t * 0.6 + i / 3) % 1;
        heart(c, -14 + i * 10 + Math.sin(t * 3 + i) * 4, -112 - u * 30, 0.9, i % 2 ? '#7fe08a' : '#ff8fb0', Math.sin(u * Math.PI));
      }
      return;
    }
    case 'grab': {
      if (!front) return;
      const ctr = boxCenter(hb) || [56, -50];
      const reach = [ctr[0] + 8, ctr[1]];
      if (ph === 'startup') grabber(c, hf[0], hf[1], lerp(hf[0] + 12, reach[0] - 10, easeIn(pt)), lerp(hf[1] + 2, reach[1], pt), 0, L);
      else if (ph === 'active') grabber(c, hf[0], hf[1], reach[0], reach[1], pt, L);
      else grabber(c, hf[0], hf[1], lerp(reach[0], hf[0] + 22, easeOut(pt)), lerp(reach[1], hf[1] + 4, easeOut(pt)), 1, L);
      return;
    }
    case 'pinch': {
      if (!front) return;
      const j = Math.sin(t * 40) * 1.5;
      grabber(c, hf[0], hf[1], 40 + j, -54, 1, L);
      if (ph === 'active') { c.save(); c.globalCompositeOperation = 'lighter'; c.fillStyle = '#ffe9a0'; kit.starPath(c, 50, -58, 4, 8, 2, t * 6); c.fill(); c.restore(); }
      return;
    }
    case 'shoulder': case 'upyougo': case 'sitdown': case 'shoo': {
      if (!front) return;
      const k = ph === 'startup' ? 0 : ph === 'active' ? easeOut(pt) : 1;
      const to = { shoulder: [-40, -104], upyougo: [10, -150], sitdown: [44, -8], shoo: [52, -64] }[anim];
      grabber(c, hf[0], hf[1], lerp(40, to[0], k), lerp(-54, to[1], k), ph === 'recovery' ? 0.2 : 1, L);
      if (anim === 'shoo' && ph !== 'startup') windLines(c, 48, -60, t, true);
      return;
    }
    default: return;
  }
}

/** A few curly gusts (umbrella lift, shoo). */
function windLines(c, x, y, t, horizontal = false) {
  c.save();
  c.strokeStyle = '#ffffff'; c.lineCap = 'round'; c.lineWidth = 2;
  for (let i = 0; i < 3; i++) {
    const ph = (t * 2.4 + i / 3) % 1;
    c.globalAlpha = Math.sin(ph * Math.PI) * 0.7;
    c.beginPath();
    if (horizontal) { const yy = y - 10 + i * 10, xx = x + ph * 26; c.moveTo(xx, yy); c.quadraticCurveTo(xx + 10, yy - 4, xx + 18, yy); }
    else { const xx = x - 14 + i * 14, yy = y + ph * 26; c.moveTo(xx, yy); c.quadraticCurveTo(xx + 4, yy + 9, xx, yy + 16); }
    c.stroke();
  }
  c.restore();
}

/** Overlays that read best on top: ram speed lines + headlight cone, stomp shockwave, spin smear. */
function overlays(c, v, info, L) {
  const m = v.move, anim = m?.anim, ph = m?.phase, pt = m?.phaseT ?? 0, t = info.time;
  if (anim === 'ram' && ph === 'active') {
    kit.speedLines(c, -96, -92, 70, 86, '#ffffff', t, { count: 8, alpha: 0.75, dir: -1, width: 2.4 });
    c.save(); c.globalCompositeOperation = 'lighter';
    const g = c.createLinearGradient(GEO.light[0], 0, GEO.light[0] + 70, 0);
    g.addColorStop(0, 'rgba(255,240,180,0.55)'); g.addColorStop(1, 'rgba(255,240,180,0)');
    c.fillStyle = g; c.beginPath(); c.moveTo(GEO.light[0], GEO.light[1] - 3); c.lineTo(GEO.light[0] + 72, GEO.light[1] - 18); c.lineTo(GEO.light[0] + 72, GEO.light[1] + 16); c.lineTo(GEO.light[0], GEO.light[1] + 3); c.closePath(); c.fill();
    c.restore();
  }
  if (anim === 'stomp' && (ph === 'active' || (ph === 'recovery' && pt < 0.5))) {
    const k = ph === 'active' ? pt : 1 + pt;
    const hb = strikeBox(m), half = (hb?.w ?? 200) / 2;
    c.save();
    c.lineCap = 'round';
    for (const s of [-1, 1]) {
      const x0 = s * 20, x1 = s * (20 + (half - 20) * Math.min(1, k * 0.9));
      c.globalAlpha = 1 - Math.max(0, k - 1) * 2;
      c.strokeStyle = OUT; c.lineWidth = 7; c.beginPath(); c.moveTo(x0, -2); c.quadraticCurveTo((x0 + x1) / 2, -14 * (1 - k * 0.5), x1, -2); c.stroke();
      c.strokeStyle = '#ffe9b0'; c.lineWidth = 3.6; c.stroke();
      for (let i = 0; i < 4; i++) {
        const xx = lerp(x0, x1, (i + 0.5) / 4), h = 6 + kit.hash01(i, s > 0 ? 3 : 5) * 8;
        c.fillStyle = '#d8c0a0'; c.strokeStyle = OUT; c.lineWidth = 1.4;
        c.beginPath(); c.moveTo(xx - 3, -1); c.lineTo(xx, -1 - h * Math.min(1, k * 2)); c.lineTo(xx + 3, -1); c.closePath(); c.fill(); c.stroke();
      }
    }
    c.restore();
  }
  if (anim === 'sputter') {
    const k = ph === 'recovery' ? 1 - pt : 1;
    if (Math.sin(t * 30) > -0.3) backfire(c, GEO.pipe[0], GEO.pipe[1], 46, 0.8 * k, t);
    for (let i = 0; i < 3; i++) {
      const u = (t * 2 + i / 3) % 1;
      c.save(); c.globalAlpha = 0.6 * (1 - u) * k;
      kit.circle(c, GEO.pipe[0] - 20 - u * 30, GEO.pipe[1] - 4 - u * 22, 6 + u * 10, '#6f6478', { outline: null });
      c.restore();
    }
  }
  if (anim === 'sitdown' && ph === 'active') {
    c.save(); c.translate(48, -40);
    kit.speedLines(c, -20, -30, 40, 40, '#ffffff', t, { count: 6, alpha: 0.75, dir: 1, width: 2.2 });
    c.restore();
  }
  if (anim === 'toss' && ph === 'active') {
    c.save(); kit.smear(c, -2, -70, 46, -2.2, -0.3, 10, '#fff6dc', 0.6); c.restore();
  }
  if (anim === 'knit' && ph !== 'startup') {
    // needles clacking: little sparkles over her lap
    c.save(); c.globalCompositeOperation = 'lighter';
    for (let i = 0; i < 2; i++) { const a = t * 9 + i * 3; kit.glow(c, 6 + Math.cos(a) * 6, -62 + Math.sin(a) * 4, 6, '#ffe9a0', 0.6); }
    c.restore();
  }
  if (anim === 'wheelie' && ph === 'active') {
    c.save(); kit.smear(c, 0, -46, 44, -Math.PI * 0.5, -Math.PI * 0.5 - TAU * 0.8 * Math.min(1, pt * 1.5), 12, '#ffffff', 0.55); c.restore();
  }
  if (anim === 'slam' && ph === 'active') {
    c.save(); c.translate(0, -60); c.rotate(-Math.PI / 2);
    kit.speedLines(c, 0, -40, 70, 80, '#ffffff', t, { count: 7, alpha: 0.7, dir: -1, width: 2.2 });
    c.restore();
  }
}

// ── The ArtDef ───────────────────────────────────────────────────────────────
export default {
  rig: 'none',
  assets: { sheet: './gertie.png', teeth: './teeth.png' },
  sheets: {
    body: { image: 'sheet', frameW: FRAME.w, frameH: FRAME.h, cols: FRAME.cols, anchor: [...FRAME.anchor], scale: FRAME.scale },
    teeth: { image: 'teeth', frameW: TEETH.w, frameH: TEETH.h, cols: TEETH.frames, anchor: [TEETH.w / 2, TEETH.h / 2], scale: 0.5 },
  },
  clips: {
    body: {
      idle: { frames: [0, 0, 1, 1, 1, 0, 0, 2, 2, 2, 0, 3], fps: 5, loop: true },   // breathe, glance, smirk, blink
      run: { frames: seq(4, 7), fps: 10, loop: true, speedFrom: 'vx' },
      jump: { frames: [8] }, fall: { frames: [9] }, jumpsquat: { frames: [16] }, land: { frames: [16] },
      glide: { frames: [10, 11], fps: 3, loop: true },
      hurt: { frames: [12] }, tumble: { frames: [13, 14], fps: 8, loop: true },
      shield: { frames: [15] }, crouch: { frames: [16] }, roll: { frames: [16] }, spotdodge: { frames: [15] }, airdodge: { frames: [9] },
      grabbing: { frames: [17] }, grabbed: { frames: [12] }, helpless: { frames: [76] }, stunned: { frames: [76] }, shieldbreak: { frames: [76] },
      taunt: { frames: [18, 19], fps: 5, loop: true }, dead: { frames: [13] }, respawn: { frames: [77] },
      lecture:  { frames: [18, 19, 18, 19, 77], fps: 5, loop: true },
      jab:      { sync: 'move', startup: [20], active: [21], recovery: [22] },
      cane:     { sync: 'move', startup: [23, 24], active: [25], recovery: [26, 27] },
      hatpin:   { sync: 'move', startup: [28], active: [29], recovery: [30] },
      knit:     { sync: 'move', startup: [31], active: [32], recovery: [33, 31] },
      handbag:  { sync: 'move', startup: [34, 35], active: [36], recovery: [37, 38], charge: [35] },
      umbrella: { sync: 'move', startup: [39], active: [40], recovery: [41], charge: [39] },
      stomp:    { sync: 'move', startup: [42], active: [43], recovery: [44], charge: [42] },
      wheelie:  { sync: 'move', startup: [45], active: [45], recovery: [45, 0] },
      pin:      { sync: 'move', startup: [46], active: [47], recovery: [48] },
      exhaust:  { sync: 'move', startup: [49], active: [49], recovery: [49, 0] },
      spray:    { sync: 'move', startup: [50], active: [51], recovery: [51, 50] },
      slam:     { sync: 'move', startup: [52], active: [52], recovery: [16] },
      toss:     { sync: 'move', startup: [53], active: [54], recovery: [55] },
      ram:      { sync: 'move', startup: [56], active: [57], recovery: [58] },
      sputter:  { sync: 'move', startup: [59], active: [59], recovery: [59, 16] },
      lift:     { sync: 'move', startup: [60], active: [40], recovery: [41] },
      tea:      { sync: 'move', startup: [61], hold: [62, 63], recovery: [61] },
      grab:     { sync: 'move', startup: [64], active: [65], recovery: [66] },
      pinch:    { sync: 'move', startup: [67], active: [67], recovery: [17] },
      shoo:     { sync: 'move', startup: [68], active: [69], recovery: [69, 0] },
      shoulder: { sync: 'move', startup: [70], active: [71], recovery: [71, 0] },
      upyougo:  { sync: 'move', startup: [72], active: [73], recovery: [73, 0] },
      sitdown:  { sync: 'move', startup: [74], active: [75], recovery: [75, 0] },
    },
  },
  bounds: { left: -124, right: 134, top: -200, bottom: 40 },
  palette: PAL,
  // duplicate picks get a different scooter (Gertie herself keeps her cardigan)
  palettes: [
    {},
    { scooter: '#2fb5a3', scooterDark: '#1b7469', scooterLight: '#8ef0dc' },
    { scooter: '#f2b631', scooterDark: '#b07a12', scooterLight: '#ffe08a' },
    { scooter: '#6d7bf0', scooterDark: '#3e45a8', scooterLight: '#b4bcff' },
  ],

  draw(ctx, v, info) {
    const c = ctx, P = info.palette, cache = info.cache, t = info.time, dt = info.dt || 1 / 60;
    const facing = v.facing < 0 ? -1 : 1;
    // persistent motion state: wheel roll, travel distance, springs
    const vxBody = (v.vx || 0) * facing;
    if (v.grounded) { cache.roll = ((cache.roll || 0) + (vxBody * dt * 60) / GEO.rear[2]) % TAU; cache.dist = (cache.dist || 0) + Math.abs(vxBody) * dt * 60; }
    const sp = cache.sp || (cache.sp = { flag: { x: 0, v: 0 }, jig: { x: 0, v: 0 } });
    const mo = info.motion;
    const bend = spring(sp.flag, clamp(-mo.lean * 0.32 + (v.grounded ? 0 : clamp(v.vy * 0.02, -0.2, 0.2)) + mo.squash * 0.35, -0.6, 0.6), dt, 90, 5);
    const jig = spring(sp.jig, mo.squash * 5, dt, 160, 7);

    const fr = info.sprite.resolve('body', v);
    const idx = clamp(fr?.frame ?? 0, 0, POSES.length - 1);
    const J = JOINTS[idx];
    const rig = rigFor(v, info, cache);

    // stage light in body space (engine mirrors body space by facing), then into the rig's frame
    const ld = info.light?.dir || { x: -0.45, y: -0.89 };
    const ln = Math.hypot(ld.x, ld.y) || 1;
    const Lb = { x: (ld.x / ln) * facing, y: ld.y / ln, rim: info.light?.rim || '#ffc48a', q: info.quality };
    const L = rotL(Lb, -(rig.tilt + rig.spin));

    // dodges: intangible flicker (half-transparent, pulsing) so they read as "can't be hit"
    const dodge = v.state === 'spotdodge' || v.state === 'airdodge' || v.state === 'roll';
    if (dodge) { c.save(); c.globalAlpha *= 0.5 + 0.15 * Math.sin(t * 40); }
    c.save();
    if (rig.shake) c.translate((info.rng() - 0.5) * rig.shake * 2, (info.rng() - 0.5) * rig.shake);
    c.translate(rig.pivot[0], rig.pivot[1]); c.rotate(rig.tilt); c.translate(-rig.pivot[0], -rig.pivot[1]);
    if (rig.spin) { c.translate(rig.spinC[0], rig.spinC[1]); c.rotate(rig.spin); c.translate(-rig.spinC[0], -rig.spinC[1]); }
    c.translate(0, rig.dy);
    c.scale(1, rig.sy);

    const battery = (v.resources?.battery ?? 100) / (v.resMax?.battery || 100);
    const m = v.move;
    const lightOn = m?.anim === 'ram' ? 1 : m?.anim === 'sputter' ? (Math.sin(t * 40) > 0.3 ? 0.6 : 0) : 0.15 + 0.1 * Math.sin(t * 2);
    scooterBack(c, P, L, { roll: cache.roll || 0, bend, bounce: mo.squash, t, speed: Math.abs(mo.lean), battery, lightOn, rev: rig.rev, jiggle: jig });

    const off = [rig.gx, rig.gy];
    props(c, v, info, J, off, L, 'back');
    // Gertie (sprite) + live rim light
    c.save();
    c.translate(SEAT.x + off[0], SEAT.y + off[1]);
    if (info.assets?.sheet) { info.sprite.drawFrame(c, 'body', idx); spriteRim(c, info, idx, L); }
    else gertieFallback(c, J, POSES[idx], L);                     // sheet failed to load: paint her from the pose joints
    c.restore();
    props(c, v, info, J, off, L, 'front');
    overlays(c, v, info, L);
    c.restore();
    if (dodge) c.restore();

    // status overlays (not rotated with the rig)
    stateCues(c, v, info);
    if (battery < 0.35) kit.blinkIcon(c, -6, -134, 'battery-low', t, { size: 13, color: '#ff5a64' });

    // particles: exhaust while driving, smoke + sparks while ramming, sparkles while sipping
    const fx = info.fx;
    if (v.grounded && Math.abs(vxBody) > 1 && !m) fx.local.smoke({ x: -54, y: -20, rate: 0.12, color: '#c9bcd6', size: [3, 6], life: [16, 26], angle: 200, speed: [0.4, 1.2] });
    if (m?.anim === 'ram' && m.phase !== 'recovery') {
      fx.local.smoke({ x: -54, y: -20, rate: 0.7, colors: ['#a89cb4', '#d8cce4'], size: [5, 10], life: [18, 30], angle: 180, speed: [1, 3] });
      if (m.phase === 'active' && v.grounded) fx.local.spark({ x: 30, y: -2, rate: 0.6, colors: ['#ffd166', '#ffffff'], angle: 200, speed: [2, 5], life: [6, 12] });
    }
    if (m?.anim === 'tea' && m.phase === 'hold') fx.local.star({ x: 4, y: -96, rate: 0.12, colors: ['#7fe08a', '#fff6c8'], size: [3, 5], life: [20, 34], angle: 270, speed: [0.4, 1] });
  },

  trail(v) {
    const m = v.move;
    if (!m || m.phase !== 'active') return null;
    const hb = strikeBox(m);
    switch (m.anim) {
      case 'cane': case 'hatpin': return hb?.x2 !== undefined ? { x: hb.x2, y: hb.y2 } : null;
      case 'handbag': case 'pin': case 'jab': { const c = boxCenter(hb); return c ? { x: c[0], y: c[1] } : null; }
      case 'ram': case 'slam': case 'stomp': case 'exhaust': case 'spray': case 'wheelie': return false;
      default: return null;
    }
  },

  entities: {
    dentures: {
      draw(ctx, e, info) {
        const L0 = info.light?.dir || { x: -0.45, y: -0.89 };
        const L = { x: L0.x * e.facing, y: L0.y, rim: info.light?.rim, q: info.quality };
        const spin = e.age * 0.32 + (e.vx || 0) * 0.02;
        // speed wisps behind + chatter marks
        ctx.save();
        ctx.globalAlpha = 0.55; ctx.strokeStyle = '#ffffff'; ctx.lineCap = 'round'; ctx.lineWidth = 2;
        const a = Math.atan2(e.vy || 0, e.vx || 1);
        for (let i = 0; i < 3; i++) {
          const o = (i - 1) * 5;
          ctx.beginPath();
          ctx.moveTo(-Math.cos(a) * 14 - Math.sin(a) * o, -Math.sin(a) * 14 + Math.cos(a) * o);
          ctx.lineTo(-Math.cos(a) * (24 + i * 3) - Math.sin(a) * o, -Math.sin(a) * (24 + i * 3) + Math.cos(a) * o);
          ctx.stroke();
        }
        ctx.restore();
        const open = [0, 0.5, 1, 0.5][(e.age >> 2) & 3];
        ctx.save();
        ctx.rotate(spin);
        if (!info.sprite.drawFrame(ctx, 'teeth', (e.age >> 2) & 3)) denturesFallback(ctx, open, rotL(L, -spin));
        ctx.restore();
        if ((e.age >> 3) & 1) {
          ctx.save(); ctx.strokeStyle = OUT; ctx.lineWidth = 1.6; ctx.lineCap = 'round';
          for (const s of [-1, 1]) { ctx.beginPath(); ctx.moveTo(s * 13, -9); ctx.lineTo(s * 17, -14); ctx.stroke(); }
          ctx.restore();
        }
      },
    },
    yarnBall: {
      draw(ctx, e, info) {
        const r = 12, rot = (e.age * (Math.abs(e.vx) || 2)) / r;
        const L0 = info.light?.dir || { x: -0.45, y: -0.89 };
        const L = { x: L0.x * e.facing, y: L0.y, rim: info.light?.rim, q: info.quality };
        // the strand back to Grandma's needles: a long wiggling tail
        ctx.save();
        ctx.lineCap = 'round';
        const wig = Math.sin(e.age * 0.25) * 4;
        ctx.strokeStyle = OUT; ctx.lineWidth = 3.6;
        ctx.beginPath(); ctx.moveTo(-r * 0.4, r * 0.8); ctx.bezierCurveTo(-r * 1.6, r * 1.1, -r * 2.2, wig, -r * 3.4, r * 0.9); ctx.stroke();
        ctx.strokeStyle = MAT.yarnA[0]; ctx.lineWidth = 1.8; ctx.stroke();
        ctx.restore();
        // ball: painted sphere + rolling wraps
        paint(ctx, S.circle(0, 0, r), MAT.yarnA, L, {
          hi: [0, 0, r], lw: 2.4, rimW: 2.6,
          detail: (g) => {
            g.strokeStyle = kit.rgba(MAT.yarnA[1], 0.85); g.lineWidth = 1.4;
            for (let i = 0; i < 5; i++) { g.beginPath(); g.ellipse(0, 0, r * 1.05, r * (0.22 + i * 0.15), rot + i * 0.63, 0, TAU); g.stroke(); }
            g.strokeStyle = kit.rgba('#ffffff', 0.45); g.lineWidth = 1;
            for (let i = 0; i < 3; i++) { g.beginPath(); g.ellipse(0, 0, r * 0.9, r * (0.3 + i * 0.2), rot * 1.3 + i, 0, TAU); g.stroke(); }
          },
        });
        // a knitting needle stuck through it (turns with the ball)
        ctx.save(); ctx.rotate(rot * 0.5);
        ctx.lineCap = 'round'; ctx.strokeStyle = OUT; ctx.lineWidth = 3.4; ctx.beginPath(); ctx.moveTo(-r * 1.3, -r * 0.2); ctx.lineTo(r * 1.4, -r * 0.6); ctx.stroke();
        ctx.strokeStyle = '#e4d6a8'; ctx.lineWidth = 1.6; ctx.stroke();
        paint(ctx, S.circle(r * 1.45, -r * 0.62, 2.4), MAT.flag, L, { lw: 1.4, rim: false });
        ctx.restore();
        // fading out near the end of its life
        if (e.lifeT < 0.15 && ((e.age >> 2) & 1)) { ctx.save(); ctx.globalAlpha = 0.5; ctx.fillStyle = '#ffffff'; ctx.beginPath(); ctx.arc(0, 0, r, 0, TAU); ctx.fill(); ctx.restore(); }
      },
    },
  },

  fx: {
    onHit(fx, ev, info) {
      const { x, y } = ev, dmg = ev.damage || 0, big = ev.strong || dmg >= 12;
      const dirA = (ev.dir || 1) < 0 ? 180 + (ev.angle ?? 40) : -(ev.angle ?? 40);   // screen degrees (y down)
      switch (ev.move) {
        case 'sideSmash':                            // the handbag spills: coins, mints, a lipstick
          fx.burst({ x, y, count: 10 + dmg, shape: 'debris', colors: ['#ffd166', '#7fe0c8', '#e8435f', '#fffdf4'], speed: [3, 9], angle: dirA, spread: 120, gravity: 0.35, life: [22, 40], size: [3, 6] });
          fx.ring({ x, y, r0: 10, r1: 70, color: '#36a58e', life: 14, width: 6 });
          fx.text({ x, y: y - 30, text: 'WHAP!', color: '#ffd166', size: 22, life: 40 });
          fx.shake(big ? 6 : 4);
          return;
        case 'fair':                                  // rolling pin: a puff of flour
          fx.burst({ x, y, count: 12, shape: 'smoke', colors: ['#ffffff', '#f4ead8'], speed: [1.5, 4], drag: 0.9, life: [18, 32], size: [6, 12] });
          fx.burst({ x, y, count: 6, shape: 'star', color: '#fff6c8', speed: [3, 6], angle: dirA, spread: 90, life: [10, 18], size: [4, 7], blend: 'lighter' });
          return;
        case 'bair':                                  // backfire: embers and soot
          fx.burst({ x, y, count: 12, shape: 'spark', colors: ['#fff3b0', '#ff8a2a', '#d6281c'], speed: [3, 8], angle: dirA, spread: 90, life: [10, 20], blend: 'lighter' });
          fx.burst({ x, y, count: 6, shape: 'smoke', colors: ['#5a4a60', '#8a7a90'], speed: [1, 3], drag: 0.9, life: [20, 34], size: [8, 14] });
          return;
        case 'uair':                                  // hairspray sparkle
          fx.burst({ x, y, count: 12, shape: 'glow', colors: ['#ffd2ec', '#e9f6ff'], speed: [1, 3], life: [14, 24], size: [8, 14], blend: 'lighter' });
          fx.burst({ x, y, count: 6, shape: 'star', color: '#ffffff', speed: [2, 5], life: [12, 20], size: [3, 6], blend: 'lighter' });
          return;
        case 'neutralSpecial':                        // CHOMP
          fx.burst({ x, y, count: 6, shape: 'shard', colors: ['#fffdf0', '#ff9fb4'], speed: [2, 6], angle: dirA, spread: 140, gravity: 0.3, life: [12, 22], size: [3, 5] });
          fx.text({ x, y: y - 22, text: 'CHOMP!', color: '#fffdf0', outline: '#a8364f', size: 16, life: 34 });
          return;
        default: {                                    // cane, hat pin, scooter: sunset stars
          fx.burst({ x, y, count: 4 + Math.round(dmg * 0.8), shape: 'star', colors: ['#ffd166', '#ffffff', '#ff8fb0'], speed: [2.5, 6 + (big ? 3 : 0)], angle: dirA, spread: 150, life: [12, 22], size: [3, 7], blend: 'lighter' });
          fx.burst({ x, y, count: 4, shape: 'streak', color: '#fff6dc', speed: [6, 11], angle: dirA, spread: 40, life: [6, 10], size: [2, 3] });
          if (big) { fx.ring({ x, y, r0: 12, r1: 64, color: '#ffd166', life: 12, width: 5 }); fx.flash('#ffd166', 0.12, 2); }
        }
      }
    },
    onHurt(fx, ev) {                                // a few petals off the hat daisy
      if ((ev.damage || 0) < 6) return;
      fx.burst({ x: ev.x, y: ev.y - 10, count: 3 + Math.round(ev.damage / 5), shape: 'debris', colors: ['#fffdf4', '#ffc531'], speed: [1, 3], gravity: 0.08, drag: 0.96, life: [30, 50], size: [2, 4] });
    },
    onLand(fx, ev) {
      const n = ev.heavy ? 6 : 3;
      for (const ang of [180, 0]) fx.burst({ x: ev.x, y: ev.y - 3, count: n, shape: 'smoke', colors: ['#e8dcc8', '#c9bcd6'], speed: [1, 3], angle: ang, spread: 25, drag: 0.9, life: [16, 28], size: [5, 9] });
      if (ev.heavy) fx.sound('squeak', { volume: 0.35, pitch: 1.5 });
    },
    onJump(fx, ev) {
      if (ev.double) {                              // umbrella-assisted hop: a puff of air
        fx.ring({ x: ev.x, y: ev.y - 6, r0: 10, r1: 46, color: '#ffd2e0', life: 14, width: 4, flat: true, alpha: 0.85 });
        fx.burst({ x: ev.x, y: ev.y - 6, count: 6, shape: 'smoke', color: '#ffffff', speed: [1, 3], angle: 90, spread: 80, drag: 0.9, life: [14, 22], size: [5, 8] });
      } else {
        fx.burst({ x: ev.x - 20 * (ev.facing || 1), y: ev.y - 3, count: 6, shape: 'smoke', colors: ['#d8cce4', '#ffffff'], speed: [1, 3], angle: 270, spread: 120, drag: 0.9, life: [14, 24], size: [5, 9] });
      }
    },
    onKO(fx, ev) {                                  // hat, pearls, petals… and the teeth, of course
      fx.burst({ x: ev.x, y: ev.y, count: 16, shape: 'debris', colors: ['#fffdf4', '#ffc531', '#d4436f'], speed: [4, 10], gravity: 0.15, life: [30, 60], size: [3, 6] });
      fx.burst({ x: ev.x, y: ev.y, count: 10, shape: 'dot', colors: ['#fffaf0', '#e8dff0'], speed: [3, 8], gravity: 0.25, life: [24, 44], size: [2, 3] });
      fx.burst({ x: ev.x, y: ev.y, count: 2, shape: { sheet: 'teeth', frame: 2 }, speed: [5, 8], gravity: 0.3, life: [40, 60], size: [1, 1] });
      fx.ring({ x: ev.x, y: ev.y, r0: 20, r1: 140, color: '#ff8fb0', life: 18, width: 8 });
      fx.flash('#ffd2e0', 0.25, 4);
      fx.sound('honk', { volume: 0.8, pitch: 0.7 });
    },
    onRespawn(fx, ev) {
      fx.burst({ x: ev.x, y: ev.y - 60, count: 18, shape: 'debris', colors: ['#fffdf4', '#ff8fb0', '#ffd166', '#7fe0c8'], speed: [2, 5], gravity: 0.12, drag: 0.97, life: [30, 50], size: [2, 4] });
      fx.text({ x: ev.x, y: ev.y - 140, text: 'Yoo-hoo!', color: '#ffffff', size: 16, life: 60 });
    },
    onMove: {
      sideSpecial(fx, ev) {
        fx.burst({ x: ev.x, y: ev.y - 16, count: 8, shape: 'smoke', colors: ['#a89cb4', '#d8cce4'], speed: [1, 3], drag: 0.9, life: [20, 32], size: [6, 11] });
        fx.text({ x: ev.x, y: ev.y - 130, text: 'VROOM!', color: '#ffd166', size: 18, life: 36 });
      },
      upSmash(fx, ev) { fx.burst({ x: ev.x, y: ev.y - 120, count: 8, shape: 'debris', colors: ['#ff8fb0', '#fff4e2'], speed: [1, 3], gravity: 0.1, life: [20, 34], size: [2, 4] }); },
      downSpecial(fx, ev) { fx.text({ x: ev.x, y: ev.y - 130, text: 'Tea time.', color: '#7fe08a', size: 14, life: 50 }); },
    },
    onEvent: {
      lecture(fx, ev) {
        fx.text({ x: ev.x, y: ev.y - 140, text: 'Back in MY day…', color: '#ffffff', outline: '#3a2340', life: 80, size: 16 });
        fx.burst({ x: ev.x + 20 * (ev.facing || 1), y: ev.y - 120, count: 3, shape: 'star', color: '#ffd166', speed: [1, 2], angle: 270, spread: 80, life: [20, 30], size: [3, 5] });
      },
      sputter(fx, ev) {
        fx.burst({ x: ev.x - 40 * (ev.facing || 1), y: ev.y - 20, count: 12, shape: 'smoke', colors: ['#4a3a52', '#6a5a78', '#8a7a90'], speed: [1, 2.5], drag: 0.92, life: [28, 44], size: [6, 12] });
        fx.text({ x: ev.x, y: ev.y - 128, text: 'pfft…', color: '#c9bcd6', size: 14, life: 40 });
        fx.sound('honk', { pitch: 0.6, volume: 0.6 });
      },
      slamDust(fx, ev) {
        fx.ring({ x: ev.x, y: ev.y, r0: 10, r1: 90, color: '#e8dcc8', life: 14, width: 6, flat: true });
        for (const ang of [180, 0]) fx.burst({ x: ev.x, y: ev.y - 4, count: 8, shape: 'smoke', colors: ['#e8dcc8', '#c9bcd6'], speed: [2, 5], angle: ang, spread: 20, drag: 0.9, life: [20, 34], size: [7, 12] });
        fx.burst({ x: ev.x, y: ev.y - 2, count: 8, shape: 'debris', color: '#b89a7a', speed: [2, 6], angle: 270, spread: 100, gravity: 0.4, life: [16, 28], size: [2, 4] });
        fx.decal({ x: ev.x, y: ev.y, shape: 'crack', r: 40, color: '#5a4a60' });
        fx.shake(5);
      },
    },
  },

  sounds: {
    taunt: 'honk',
    chatter: { type: 'square', freq: [1300, 900], dur: 0.16, gain: 0.25, vibrato: { rate: 28, depth: 0.35 } },
    sideSpecial: { type: 'sawtooth', freq: [70, 180], dur: 0.45, gain: 0.35, vibrato: { rate: 18, depth: 0.12 } },
  },

  portrait(ctx, size, info) {
    // warm sunset disc behind her head, then the idle pose framed on the face
    const g = ctx.createRadialGradient(size * 0.45, size * 0.4, size * 0.05, size * 0.5, size * 0.5, size * 0.6);
    g.addColorStop(0, '#ffe2b8'); g.addColorStop(0.6, '#ffb08a'); g.addColorStop(1, 'rgba(255,140,140,0)');
    ctx.fillStyle = g; ctx.fillRect(0, 0, size, size);
    info.drawIdle(ctx, { focus: { x: -2, y: -95 }, zoom: size / 72 });
  },
};
